server:
  port: 8899
  servlet:
    context-path:

spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:sqlite:/Users/fish/bs_project/md-api-engine/src/main/resources/bcp-demo.db?date_string_format=yyyy-MM-dd HH:mm:ss
    driverClassName: org.sqlite.JDBC
    initialSize: 3
    minIdle: 3
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: SELECT '1' from sqlite_master
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: false
    maxPoolPreparedStatementPerConnectionSize: -1
    filters: stat,slf4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
  #hibernate5需要自己配置方言
  jpa:
    database-platform: com.bsi.framework.core.sqlite.SQLiteDialect
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    thymeleaf:
      cache: false

jasypt:
  encryptor:
    password: FElzKb2pGHg0QNqSpX2MHs08